#
# Module manifest for module 'Isystem.PowerShell.PowerPlatform.Dataverse'
#
# Generated by: Ondrej Kracmar
#
# Generated on: 09/22/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Isystem.PowerShell.PowerPlatform.Dataverse.psm1'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '4f78bc29-fd8d-444c-a449-a244eeb23a79'

# Author of this module
Author = 'Ondrej Kracmar'

# Company or vendor of this module
CompanyName = 'Isystem'

# Copyright statement for this module
Copyright = '(c) Isystem. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Session-based cmdlets for Microsoft Dataverse (Power Platform, Dynamics 365): CRUD, upsert by alternate key, batches, transactions, FetchXML and paging. Authenticates with connection string, client secret, certificate, managed identity, Isystem.AzAuth modes, or a delegated user sign-in whose token cache the caller stores (Key Vault) for environments without application users.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.5'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Isystem.PowerShell.PowerPlatform.Dataverse.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Connect-PSDataverse', 'Disconnect-PSDataverse', 
               'Get-PSDataverseConnection', 'Get-PSDataverseRecord', 
               'Get-PSDataverseRecordCount', 'Find-PSDataverseRecord', 
               'Test-PSDataverseRecord', 'New-PSDataverseRecord', 
               'Set-PSDataverseRecord', 'Remove-PSDataverseRecord', 
               'Invoke-PSDataverseBatch', 'Invoke-PSDataverseTransaction', 
               'Invoke-PSDataverseFetchXml', 'Get-PSDataverseTokenCache'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Dataverse','PowerPlatform','Dynamics365','CRM','PowerApps','Upsert','PSEdition_Core','Windows','Linux','MacOS'

        # A URL to the license for this module.
        LicenseUri = 'https://dev.azure.com/i-system/PSModules/_git/Isystem.PowerShell.PowerPlatform?path=/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://dev.azure.com/i-system/PSModules/_git/Isystem.PowerShell.PowerPlatform'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '## [1.0.1] - 2026-09-21

### Fixed
- README shipped with 1.0.0 still described a source build and `bin/` import - meaningless on
  the GitHub mirror, which carries no source. It now opens with the mirror notice, installs from
  the PowerShell Gallery, and documents the Isystem.AzAuth and delegated (portable token cache)
  authentication modes and the upsert section that 1.0.0 introduced. No code changes.
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

